---
title: "Lesson 2 - Indexing and Data Exploration"
author: "Brennan T. Beal"
date: '2020-07-01T21:13:14-05:00'
tags:
- R Markdown
- Lessons
- Intro
categories: R
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Welcome to The University of Washington and your crash course on R. Note that this class will not be incredibly robust (we have three days) but it will aim to provide you the tools necessary to do well in your stats classes and beyond. Futher, I believe several of you will take a semester long course in R. You'll be ahead of that game but will go into more depth during that class.\
\
My goal for this course is for you to become acquainted with R and all the basic capabilities. But, importantly, I will also teach you how to ask good questions and solve problems on your own - this is a skill that came late to me and can save you a lot of time (maybe tears) when you get stuck (you will get stuck).\
\
Finally, know that this is just supposed to be a primer for what we do in class. You're expected to at least skim the document; however, we will go over all of this in class as well so that you can ask questions while we go! This will be here for backup.\
\
For our first lesson, I want to discuss some of the basics:

  1. R as a Fancy Calculator
  2. R and Logical Operations
  3. Basic Data Structures in R
  4. Asking Good Questions
