baseURL = "https://zealous-hawking-ce0a3d.netlify.app/"
languageCode = "en-us"
title = "Intro to R"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Brennan T. Beal"
    description = "An introductory tour of R for incoming UW CHOICE PhDs and Fellows"
    githubUsername = "#"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["r"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/modules"
    name = "Modules"
    weight = 3

[[menu.main]]
    url = "/practice/problemsets"
    name = "Problem Sets"
    weight = 4
[[menu.main]]
    url = "/practice/solns"
    name = "Solutions"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://github.com/btbeal"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/BealBrennan"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/btbeal/"
    name = "linkedin"
    weight = 4

