---
title: "Lesson 2 - Indexing and Data Exploration"
author: "Brennan T. Beal"
date: 2020-07-01T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "Lessons", "Intro"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In the previous lesson we covered the very basics of R. We discussed that R can be a fancy calculator, interpret logical arguments, and some fun facts sprinkled throughout. In addition, we covered basic data types and structures. Alone, this is good information to know... and is indeed the very bare bones introduction... but we are here to look at data - to manipulate data in a meaningful way. The first step towards data exploration is learning how to find values in a data set. We call this indexing.\
\
Indexing is one of the most parts of R and extends into everything you'll do from here one out. First, we will learn how to index and manipulate data "the hard way". Then, I will show you a much easier way with `tidyverse`. Of course, you could just skip to the `tidyverse` part but you are going to be sad when you need to write a loop in the next lesson. So, stick with me.\

\
In this lesson:

  1. Indexing and Manipulating Vectors
  2. Indexing and Manipulating Dataframes as an extension
  3. `Tidyverse` 
